[tool.semantic_release]
branch = "main" # ou "main" selon votre branche principale
version_variable = "setup.py:__version__"
commit_message = "chore(release): create new version {version}"
github_token = "${GH_TOKEN}"