name: Workflow Master

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # important pour semantic-release

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pylint flask sqlalchemy flask-migrate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exécution de Pylint
        run: |
          pylint $(find . -name "*.py" -not -path "./migrations/*") --disable=W

      #- name: Migration de la base de données
      #  run: |
      #    flask db upgrade

      - name: Release avec semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pip install python-semantic-release
          semantic-release publish