name: Workflow Master

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint flask flask_sqlalchemy flask_migrate psycopg2-binary

      - name: Vérification de PostgreSQL
        run: |
          echo "Attente de PostgreSQL"
          until PGPASSWORD=${{ secrets.POSTGRES_PASSWORD_MAIN }} psql -h 51.255.51.83 -p 5435 -U prod_user -d prod_db -c '\q'; do
            sleep 1
          done
          echo "PostgreSQL est prêt."

      - name: Définir la variable DATABASE_URL
        run: |
          echo "DATABASE_URL=postgresql://prod_user:${{ secrets.POSTGRES_PASSWORD_MAIN }}@51.255.51.83:5435/prod_db" >> $GITHUB_ENV

      - name: Exécution de Pylint
        run: pylint $(find . -name "*.py" -not -path "./migrations/*") --disable=W

      - name: Lancer les migrations
        run: |
          flask db migrate -m "Mise à jour de la base de données"
          flask db upgrade

      - name: Commit des changements de migration
        run: |
          git config --local user.email "migrations@depsec.org"
          git config --local user.name "Migrations"
          git add --dry-run --ignore-missing migrations/versions/*.py
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Ajout automatique des fichiers de migration"
            echo "FICHIERS DE MIGRATION COMMITTÉS"
            git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push origin ${{ github.ref_name }}
          else
            echo "AUCUN CHANGEMENT DE FICHIER DE MIGRATION À COMMITTER"
          fi
      - name: Release avec semantic-release
        uses: python-semantic-release/python-semantic-release@v9.21.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          root_options: -vv
