name: Workflow Test

on:
  push:
    branches:
      - 'test'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      
      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pylint flask sqlalchemy flask-migrate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Exécution de Pylint
        run: |
          pylint $(git ls-files '*.py') --ignore=migrations
      
      - name: Générer les migrations de la base de données
        run: |
          flask db migrate -m "Mise à jour de la base de données"
      
      - name: Appliquer les migrations de la base de données
        run: |
          flask db upgrade
