name: Workflow Test

on:
  push:
    branches:
      - 'test'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3
      
      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint flask flask_sqlalchemy flask_migrate psycopg2-binary
      
      - name: Vérification de PostgreSQL
        run: |
          echo "Attente de PostgreSQL..."
          until PGPASSWORD=${{ secrets.POSTGRES_PASSWORD_TEST }} psql -h 51.255.51.83 -U test_user -d test_db -c '\q'; do
            sleep 1
          done
          echo "PostgreSQL est prêt."
      
      - name: Définir la variable DATABASE_URL
        run: echo "DATABASE_URL=postgresql://test_user:${{ secrets.POSTGRES_PASSWORD_TEST }}@51.255.51.83:5433/test_db" >> $GITHUB_ENV
      
      - name: Lancer les migrations
        run: |
          flask db stamp head  # Marque la base comme étant à jour
          flask db migrate -m "Mise à jour de la base de données"
          flask db upgrade
      
      - name: Exécution de Pylint
        run: pylint $(find . -name "*.py" -not -path "./migrations/*") --disable=W
